### ISSUE TITLE
NEP-181: invalid type: string \\\"50\\\", expected u64

### ISSUE THREAD

**Issue by ilyar** [near/near-wallet#1845]
**Problem**

```
errors.js:18 Uncaught (in promise) Error: Querying call/collection.jmw.near/nft_tokens_for_owner,ZMKC1ggrxR5fACQFWMt9eTYvf3AYLdbUWUFQLZufKt7duBJxQJmHTEMNMAEkicp4XpTGKX7c8ZYWX9i26qGZ8p failed: wasm execution failed with error: FunctionCallError(HostError(GuestPanic { panic_msg: "panicked at \'Failed to deserialize input from JSON.: Error(\"invalid type: string \\\"50\\\", expected u64\", line: 1, column: 62)\', contract/arterra/arterra.rs:138:1" })).
{
  "error": "wasm execution failed with error: FunctionCallError(HostError(GuestPanic { panic_msg: \"panicked at \\'Failed to deserialize input from JSON.: Error(\\\"invalid type: string \\\\\\\"50\\\\\\\", expected u64\\\", line: 1, column: 62)\\', contract/arterra/arterra.rs:138:1\" }))",
  "logs": [],
  "block_height": 40699732,
  "block_hash": "8ZWG5GmKvVfPXtEZucbeYNnWg8SvA2zsGTrRXAsGuaoh"
}
    at f.query (json-rpc-provider.js:80)
    at async g.viewFunction (account.js:271)
```

https://nomicon.io/Standards/NonFungibleToken/Enumeration.html

```rust
// Get list of all tokens owned by a given account
//
// Arguments:
// * `account_id`: a valid NEAR account
// * `from_index`: a string representing an unsigned 128-bit integer,
//    representing the starting index of tokens to return
// * `limit`: the maximum number of tokens to return
//
// Returns a paginated list of all tokens owned by this account
function nft_tokens_for_owner(
  account_id: string,
  from_index: string|null, // default: 0
  limit: number|null, // default: unlimited (could fail due to gas limit)
): Token[] {}
```

https://github.com/ilyar/near-sdk-rs/blob/aeceb993eed7e7a9d6baf9e8e31b1034a663caa8/near-contract-standards/src/non_fungible_token/enumeration/enumeration_impl.rs#L60
```rust
    fn nft_tokens_for_owner(
        &self,
        account_id: ValidAccountId,
        from_index: Option<U128>,
        limit: Option<u64>,
    ) -> Vec<Token> {
```

**Expected Behavior**

```
POST https://rpc.mainnet.near.org/
Content-Type: application/json; charset=utf-8

{
  "method": "query",
  "params": [
    "call/collection.jmw.near/nft_tokens_for_owner",
    "pxijmr9QZzH1FZsyRdUaHRr9KTxscYZodCnC8EhFBCX72NwGoYa41RwVaxFZNsdGc1prasreUq8zi4CSAHT7ctU3eC"
  ],
  "id": 140,
  "jsonrpc": "2.0"
}
```

**Steps to reproduce**

```
POST https://rpc.mainnet.near.org/
Content-Type: application/json; charset=utf-8

{
  "method": "query",
  "params": [
    "call/collection.jmw.near/nft_tokens_for_owner",
    "ZMKC1ggrxR5fACQFWMt9eTYvf3AYLdbUWUFQLZufKt7duBJxQJmHTEMNMAEkicp4XpTGKX7c8ZYWX9i26qGZ8p"
  ],
  "id": 140,
  "jsonrpc": "2.0"
}
```

**Comment by Patrick1904** [comment]
This has been merged to master in https://github.com/near/near-wallet/pull/1848
