### ISSUE TITLE
Wallet javascript error prevents it from rendering

### ISSUE THREAD

**Issue by dimaswift** [near/near-wallet#2378]
**Problem**
After creating and funding an account with NEAR and using it for few hours - it stopped working. In Chrome console it throws an error and screen is just a white blank.

Reproduced on Chrome, Edge, Firefox, Chrome iOS. Both on incognito and regular mode

Clearing cache, cookies, changing browser or device does not help.

**Expected Behavior**
Wallet should render normally

**Steps to reproduce**

1. Go to wallet.near.org
2. Recover account
3. Go to wallet
4. See wallet blink for a second, then goes to white screen.

**Error log:**

Chrome:

```
src.3fe9fd3b.js:3425 TypeError: Cannot read properties of null (reading 'access_key')
    at w (src.3fe9fd3b.js:3303:4139)
    at E (src.3fe9fd3b.js:3303:4032)
    at ua (src.3fe9fd3b.js:27:58593)
    at Ro (src.3fe9fd3b.js:27:104856)
    at Lu (src.3fe9fd3b.js:27:97578)
    at Ru (src.3fe9fd3b.js:27:97503)
    at Cu (src.3fe9fd3b.js:27:94435)
    at src.3fe9fd3b.js:27:45986
    at exports.unstable_runWithPriority (src.3fe9fd3b.js:23:3996)
    at ri (src.3fe9fd3b.js:27:45696)
    at oi (src.3fe9fd3b.js:27:45932)
    at ai (src.3fe9fd3b.js:27:45867)
    at _u (src.3fe9fd3b.js:27:94819)
    at Object.notify (src.3fe9fd3b.js:80:230)
    at Object.notifyNestedSubs (src.3fe9fd3b.js:80:825)
    at i (src.3fe9fd3b.js:80:659)
    at w (src.3fe9fd3b.js:136:2576)
    at src.3fe9fd3b.js:3528:948
    at src.3fe9fd3b.js:946:151
    at src.3fe9fd3b.js:167:980
    at dispatch (src.3fe9fd3b.js:136:5210)
    at src.3fe9fd3b.js:3279:892

```

Edge:
```

TypeError: t is null
    w ActivityBox.js:175
    E ActivityBox.js:169
    React 6
    unstable_runWithPriority scheduler.production.min.js:19
    React 4
    Redux 6
    u middleware.js:26
    Redux 2
```

**Comment by philazer** [comment]
Same behavior in edge, chrome, brave.
Below console error :
    TypeError: Cannot read properties of null (reading 'deposit')
    at I (ActivityBox.js:193:70)
    at E (ActivityBox.js:170:15)
    at ua (react-dom.production.min.js:153:1)
    at Ro (react-dom.production.min.js:261:1)
    at Lu (react-dom.production.min.js:246:1)
    at Ru (react-dom.production.min.js:246:1)
    at Cu (react-dom.production.min.js:239:1)
    at react-dom.production.min.js:123:1
    at exports.unstable_runWithPriority (scheduler.production.min.js:19:1)
    at ri (react-dom.production.min.js:122:1)
    at oi (react-dom.production.min.js:123:1)
    at ai (react-dom.production.min.js:122:1)
    at _u (react-dom.production.min.js:240:1)
    at Object.notify (Subscription.js:15:7)
    at Object.notifyNestedSubs (Subscription.js:85:15)
    at i (Subscription.js:90:20)
    at w (redux.js:296:32)
    at index.js:18:16
    at index.js:20:16
    at middleware.js:26:18
    at dispatch (redux.js:659:28)
    at index.js:31:15
My deposit is not null!

**Comment by dimaswift** [comment]
looks live issue has been resolved
