### ISSUE TITLE
New Account Unusable after Backend RPC Timeout

### ISSUE THREAD

**Issue by near-guildnet** [near/near-wallet#842]
When creating a account and setting a recover option the account becomes unusable if an RPC timeout is encountered on the backend. The account is not usable in the browser and recovery options no longer work.

Executing (default): SELECT "id", "accountId", "createdAt", "updatedAt" FROM "Accounts" AS "Account" WHERE "Account"."accountId" = 'pool.guildnet' LIMIT 1;
Executing (default): SELECT "id", "kind", "detail", "publicKey", "securityCode", "requestId", "createdAt", "updatedAt", "AccountId" FROM "RecoveryMethods" AS "RecoveryMethod" WHERE ("RecoveryMethod"."AccountId" = 19 AND ("RecoveryMethod"."kind" = 'email' AND "RecoveryMethod"."detail" = 'test@test.com' AND "RecoveryMethod"."securityCode" = '085108'));
Executing (default): SELECT "createdAt", "detail", "kind", "publicKey", "securityCode" FROM "RecoveryMethods" AS "RecoveryMethod" WHERE "RecoveryMethod"."AccountId" = 19;
  --> POST /account/validateSecurityCodeForTempAccount 200 521ms 122b
  <-- OPTIONS /account
  --> OPTIONS /account 204 1ms
  <-- POST /account
Error:  TypedError: [-32000] Server error: Timeout error
    at JsonRpcProvider.sendJsonRpc (/home/blaze/near-contract-helper/node_modules/near-api-js/lib/providers/json-rpc-provider.js:145:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Account.signAndSendTransaction (/home/blaze/near-contract-helper/node_modules/near-api-js/lib/account.js:98:22)
    at async /home/blaze/near-contract-helper/app.js:71:16
    at async withNear (/home/blaze/near-contract-helper/middleware/near.js:98:5)
    at async /home/blaze/near-contract-helper/app.js:14:9
    at async cors (/home/blaze/near-contract-helper/node_modules/@koa/cors/index.js:98:16)
    at async logger (/home/blaze/near-contract-helper/node_modules/koa-logger/index.js:67:7) {
  type: 'UntypedError'
} {"type":"UntypedError"}

**Comment by bowenwang1996** [comment]
> When creating a account and setting a recover option the account

Looks like you are talking about wallet. If so, you should open an issue here https://github.com/near/near-wallet

**Comment by htafolla** [comment]
bowenwang1996 is that not this repo? ☕ 😄

**Comment by kcole16** [comment]
This should be fixed now
